# 🐼 Pandas Code Lab
## Beginner Hands-On Practical Session

**Goal:** Learn Pandas by writing and running code in Jupyter Notebook.

### Topics
- Series
- DataFrame
- Inspecting data
- Selecting columns
- Filtering rows
- Adding/updating columns
- Missing values
- Basic statistics
- GroupBy
- Mini project

## 1. Setup

Run this cell first.

In [1]:
import pandas as pd

print(pd.__version__)

2.2.2

## 2. Series

A **Series** is a one-dimensional labelled data structure.

### Example

In [2]:
marks = pd.Series([80, 75, 90, 65, 88])
print(marks)

0    80
1    75
2    90
3    65
4    88
dtype: int64

### 🧪 Practice 1
Create a Series called `ages` containing:

`20, 21, 19, 22, 20`

Then print the Series and print the value at index `2`.

In [3]:
ages = pd.Series([20,21,19,22,20])

print(ages)

0    20
1    21
2    19
3    22
4    20
dtype: int64

## 3. Create a DataFrame

A **DataFrame** is a two-dimensional table with rows and columns.

In [4]:
data = {
    "Name": ["Arun", "Priya", "Rahul", "Divya", "Kiran"],
    "Department": ["AI", "DS", "AI", "CSE", "DS"],
    "Marks": [85, 92, 76, 88, 95],
    "Attendance": [90, 95, 75, 82, 98]
}

df = pd.DataFrame(data)
df

    Name Department  Marks  Attendance
0   Arun         AI     85          90
1  Priya         DS     92          95
2  Rahul         AI     76          75
3  Divya        CSE     88          82
4  Kiran         DS     95          98

## 4. Inspect the DataFrame

Try these commonly used commands.

In [5]:
print(df.head(2))
print(df.tail(2))
print(df.shape)
print(df.columns)
print(df.dtypes)

    Name Department  Marks  Attendance
0   Arun         AI     85          90
1  Priya         DS     92          95
    Name Department  Marks  Attendance
3  Divya        CSE     88          82
4  Kiran         DS     95          98
(5, 4)
Index(['Name', 'Department', 'Marks', 'Attendance'], dtype='object')
Name          object
Department    object
Marks          int64
Attendance     int64
dtype: object

### 🧪 Practice 2
1. Display the first 3 rows.
2. Display the last 2 rows.
3. Find the number of rows and columns.
4. Display only the column names.

In [6]:
print(df.head(3))
print(df.tail(2))
print(df.shape)
print(df.columns)

    Name Department  Marks  Attendance
0   Arun         AI     85          90
1  Priya         DS     92          95
2  Rahul         AI     76          75
    Name Department  Marks  Attendance
3  Divya        CSE     88          82
4  Kiran         DS     95          98
(5, 4)
Index(['Name', 'Department', 'Marks', 'Attendance'], dtype='object')

## 5. Selecting Columns

### One column

In [7]:
df["Name"]

0     Arun
1    Priya
2    Rahul
3    Divya
4    Kiran
Name: Name, dtype: object

### Multiple columns

In [8]:
df[["Name", "Marks"]]

    Name  Marks
0   Arun     85
1  Priya     92
2  Rahul     76
3  Divya     88
4  Kiran     95

### 🧪 Practice 3
Display:
1. `Name` and `Department`
2. `Name`, `Marks`, and `Attendance`

In [9]:
df[["Name" ,"Department"]]

    Name Department
0   Arun         AI
1  Priya         DS
2  Rahul         AI
3  Divya        CSE
4  Kiran         DS

## 6. Filtering Rows

Find students who scored more than 80.

In [10]:
df

    Name Department  Marks  Attendance
0   Arun         AI     85          90
1  Priya         DS     92          95
2  Rahul         AI     76          75
3  Divya        CSE     88          82
4  Kiran         DS     95          98

In [11]:
df=df[df["Attendance"]>90]
df["Name"][df["Marks"] > 80]

1    Priya
4    Kiran
Name: Name, dtype: object

In [12]:
df[df["Marks"] > 80]

    Name Department  Marks  Attendance
1  Priya         DS     92          95
4  Kiran         DS     95          98

### 🧪 Practice 4
Write code to find:
1. Students with marks greater than 85.
2. Students with attendance greater than 90.
3. Students from the `AI` department.
4. Students with marks less than 80.

In [13]:
print("students with marks greater than 85")
df[df["Marks"]>85]

students with marks greater than 85

    Name Department  Marks  Attendance
1  Priya         DS     92          95
4  Kiran         DS     95          98

In [14]:
print("Student with attendance greater than 90")
df[df["Attendance"]>90]

Student with attendance greater than 90

    Name Department  Marks  Attendance
1  Priya         DS     92          95
4  Kiran         DS     95          98

In [15]:
print("Student with  AI department")

df["Department"] == "AI"

Student with  AI department

1    False
4    False
Name: Department, dtype: bool

## 7. Multiple Conditions

Use `&` for AND and `|` for OR.

Example: marks greater than 80 AND attendance greater than 85.

In [16]:
df[(df["Marks"] > 80) & (df["Attendance"] > 85)]

    Name Department  Marks  Attendance
1  Priya         DS     92          95
4  Kiran         DS     95          98

### 🧪 Practice 5
Find students who:
1. Have marks greater than 80 AND attendance greater than 90.
2. Are from AI OR DS department.

In [17]:
# Write your code here
df[(df["Marks"] > 80) & (df["Attendance"] > 85)]

    Name Department  Marks  Attendance
1  Priya         DS     92          95
4  Kiran         DS     95          98

In [18]:
df[(df["Department"] == "AI") | (df["Department"] == "DS")]

    Name Department  Marks  Attendance
1  Priya         DS     92          95
4  Kiran         DS     95          98

In [19]:
df["Marks"] = df["Marks"] + 5
df

C:\Users\sarat\AppData\Local\Temp\ipykernel_8976\1519246995.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Marks"] = df["Marks"] + 5

    Name Department  Marks  Attendance
1  Priya         DS     97          95
4  Kiran         DS    100          98

In [20]:
df["eligible_for_exam"]=df["Attendance"]>75
df

C:\Users\sarat\AppData\Local\Temp\ipykernel_8976\444487622.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["eligible_for_exam"]=df["Attendance"]>75

    Name Department  Marks  Attendance  eligible_for_exam
1  Priya         DS     97          95               True
4  Kiran         DS    100          98               True

In [21]:
df["Pass"] = df["Marks"] >= 40
df

C:\Users\sarat\AppData\Local\Temp\ipykernel_8976\3207990321.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Pass"] = df["Marks"] >= 40

    Name Department  Marks  Attendance  eligible_for_exam  Pass
1  Priya         DS     97          95               True  True
4  Kiran         DS    100          98               True  True

### 🧪 Practice 6
1. Create a `Bonus` column by adding 5 marks.
2. Create a `Final_Marks` column by adding `Marks + Bonus`.
3. Create a `High_Performer` column that is `True` when marks are 85 or above.

In [42]:
# Write your code here

# 1. Create a Bonus column by adding 5 marks
df.loc[:, 'Bonus'] = 5
df.loc[:, 'Final_Marks'] = df['Marks'] + df['Bonus']
df.loc[:, 'High_Performer'] = df['Marks'] >= 85

## 9. Missing Values

Create a DataFrame containing a missing mark.

In [46]:
data_missing = {
    "Name": ["Arun", "Priya", "Rahul", "Divya"],
    "Marks": [85, None, 76, 90]
}

df_missing = pd.DataFrame(data_missing)
df_missing

    Name  Marks
0   Arun   85.0
1  Priya    NaN
2  Rahul   76.0
3  Divya   90.0

Useful methods:

- `isnull()` → find missing values
- `isnull().sum()` → count missing values
- `fillna()` → replace missing values

In [24]:
print(df_missing.isnull())
print(df_missing.isnull().sum())

    Name  Marks
0  False  False
1  False   True
2  False  False
3  False  False
Name     0
Marks    1
dtype: int64

### 🧪 Practice 7
Fill the missing mark using the **mean of the Marks column**.

In [45]:
df = df.copy()

df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
df

,Name,Department,Marks,Attendance,eligible_for_exam,Pass,Bonus,Final_marks,High_Performer,bonus,Final_Marks
1,Priya,DS,97,95,True,True,5,199,True,5,102
4,Kiran,DS,100,98,True,True,5,205,True,5,105

## 10. Basic Statistics

In [25]:
print("Mean:", df["Marks"].mean())
print("Maximum:", df["Marks"].max())
print("Minimum:", df["Marks"].min())
print("Total:", df["Marks"].sum())
print(df["Marks"].describe())
print(df.info())

Mean: 98.5
Maximum: 100
Minimum: 97
Total: 197
count      2.00000
mean      98.50000
std        2.12132
min       97.00000
25%       97.75000
50%       98.50000
75%       99.25000
max      100.00000
Name: Marks, dtype: float64
<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 1 to 4
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               2 non-null      object
 1   Department         2 non-null      object
 2   Marks              2 non-null      int64
 3   Attendance         2 non-null      int64
 4   eligible_for_exam  2 non-null      bool
 5   Pass               2 non-null      bool
dtypes: bool(2), int64(2), object(2)
memory usage: 84.0+ bytes
None

### 🧪 Practice 8
Find:
1. Average attendance
2. Highest attendance
3. Lowest attendance
4. Total marks

In [26]:
# Write your code here

## 11. GroupBy

Find the average marks for each department.

In [27]:
df.groupby("Department")["Marks"].mean()

Department
DS    98.5
Name: Marks, dtype: float64

### 🧪 Practice 9
1. Find the average attendance for each department.
2. Find the maximum marks for each department.
3. Count the number of students in each department.

In [50]:
# Write your code here
df.groupby("Department")["Attendance"].mean()
df.groupby("Department")["Marks"].max()
df.groupby("Department").size()

Department
DS    2
dtype: int64

# 🚀 Mini Project: Student Performance Analyzer

Use the following dataset.

In [51]:
project_data = {
    "Name": ["Arun", "Priya", "Rahul", "Divya", "Kiran", "Meena", "Vijay", "Anu"],
    "Department": ["AI", "DS", "AI", "CSE", "DS", "AI", "CSE", "DS"],
    "Marks": [85, 92, 67, 78, 95, 72, 88, 81],
    "Attendance": [90, 95, 75, 82, 98, 79, 91, 85]
}

students = pd.DataFrame(project_data)
students

    Name Department  Marks  Attendance
0   Arun         AI     85          90
1  Priya         DS     92          95
2  Rahul         AI     67          75
3  Divya        CSE     78          82
4  Kiran         DS     95          98
5  Meena         AI     72          79
6  Vijay        CSE     88          91
7    Anu         DS     81          85

## 🎯 Mini Project Tasks

Solve these independently.

1. Display the first 5 students.
2. Display only `Name` and `Marks`.
3. Find students who scored more than 80.
4. Find students with attendance greater than 85.
5. Find students with marks > 80 AND attendance > 85.
6. Find the average marks.
7. Find the highest-scoring student.
8. Find average marks for each department.
9. Add a `Performance` column: `Excellent` if marks >= 90, otherwise `Good`.
10. Find the number of students in each department.

In [52]:
# 🚀 Write your mini-project solution here
print(df.head())
print(df[["Name", "Marks"]])
print(df[df["Marks"] > 80])
print(df[df["Attendance"] > 85])
print(df[(df["Marks"] > 80) & (df["Attendance"] > 85)])
print(df["Marks"].mean())
print(df.loc[df["Marks"].idxmax()])
print(df.groupby("Department")["Marks"].mean())
df["Performance"] = df["Marks"].apply(
    lambda x: "Excellent" if x >= 90 else "Good"
)
print(df)
print(df.groupby("Department").size())

    Name Department  Marks  Attendance  eligible_for_exam  Pass  Bonus  \
1  Priya         DS     97          95               True  True      5
4  Kiran         DS    100          98               True  True      5

   Final_marks  High_Performer  bonus  Final_Marks
1          199            True      5          102
4          205            True      5          105
    Name  Marks
1  Priya     97
4  Kiran    100
    Name Department  Marks  Attendance  eligible_for_exam  Pass  Bonus  \
1  Priya         DS     97          95               True  True      5
4  Kiran         DS    100          98               True  True      5

   Final_marks  High_Performer  bonus  Final_Marks
1          199            True      5          102
4          205            True      5          105
    Name Department  Marks  Attendance  eligible_for_exam  Pass  Bonus  \
1  Priya         DS     97          95               True  True      5
4  Kiran         DS    100          98               True  True      5

   Final_marks  High_Performer  bonus  Final_Marks
1          199            True      5          102
4          205            True      5          105
    Name Department  Marks  Attendance  eligible_for_exam  Pass  Bonus  \
1  Priya         DS     97          95               True  True      5
4  Kiran         DS    100          98               True  True      5

   Final_marks  High_Performer  bonus  Final_Marks
1          199            True      5          102
4          205            True      5          105
98.5
Name                 Kiran
Department              DS
Marks                  100
Attendance              98
eligible_for_exam     True
Pass                  True
Bonus                    5
Final_marks            205
High_Performer        True
bonus                    5
Final_Marks            105
Name: 4, dtype: object
Department
DS    98.5
Name: Marks, dtype: float64
    Name Department  Marks  Attendance  eligible_for_exam  Pass  Bonus  \
1  Priya         DS     97          95               True  True      5
4  Kiran         DS    100          98               True  True      5

   Final_marks  High_Performer  bonus  Final_Marks Performance
1          199            True      5          102   Excellent
4          205            True      5          105   Excellent
Department
DS    2
dtype: int64